name: Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant hassfest

      - name: Run Hassfest validation
        run: |
          hassfest --path ./custom_components/starship_tracker/

      - name: Validate HACS
        uses: hacs/action@main
        with:
          category: integration
